# dist: yakkety  # silently ignored and trusty is used
# dist: xenial   # silently ignored and trusty is used
dist: trusty     # Ubuntu 14.04.5 LTS https://wiki.ubuntu.com/Releases
sudo: true
sudo: required

services:
  - docker
language: scala  # NOT a Python repo!
scala:
   - 2.11.2
#language: python
#python:
#    - "2.7.13"
#    - "3.6.0"
#   - "nightly"  # currently points to 3.7-dev
# command to install dependencies
before_install:
    - build https://github.com/docker-library/python.git#:3.6/alpine`.
    - 9
    - docker pull python:3.6.1
    - 9
#   - source install_python3.sh
    - python -V
    - pip -V
    - python3 -V
    - pip3 -V
    - pip3 install --upgrade pip setuptools
    - pip3 install --upgrade flake8
before_script:
    - flake8 . --count --max-line-length=127 --statistics --exit-zero
script:
    - flake8 . --count --max-line-length=127 --select=E999  # Stop build on syntax errors
notifications:
    on_success: change
    on_failure: never  # always
