sudo: false
language: scala  # NOT a Python repo!
scala:
   - 2.11.2
#language: python
#python:
#    - "2.7.13"
#    - "3.6.0"
#   - "nightly"  # currently points to 3.7-dev
# command to install dependencies
# before_install:
install:
    - python -V     # Python 2.7.3 !!!
    - # python3 -V  # Error!
    - pip -V        # pip 6.0.8 from /usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg (python 2.7)
    - # pip install --upgrade pip setuptools  # Error
    - # pip3 -V     # Error!
    - echo $HOME
    - echo ~
    - echo $PATH
    - pwd
    - ls --help
    - # cd ~
    - pwd
    - ls
    - #mkdir Python3
    - #cd Python3
    - #pwd
    - wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.6.0.tar.bz2
    - tar xjf python-3.6.0.tar.bz2
    - # source ./home/travis/virtualenv/python3.6.0/bin/activate
    - whereis --help
    - whereis python3
    - which --help
    - # which python3
    - python -V
    - pip -V
    - python3 -V
    - pip3 -V
    - ls ./home/travis/virtualenv/python3.6.0/bin
    - ./home/travis/virtualenv/python3.6.0/bin/python3 -V
    - ./home/travis/virtualenv/python3.6.0/bin/pip3 -V
    - ls
    - # ls -R
    - python --version
    - whereis python3
    - # which python3
    - # ~/virtualenv/python3.6.0/bin/Python -V
    - # ~/virtualenv/python3.6.0/bin/pip -V
    - # ls -R ~/virtualenv/py*
    - ls -R | grep virtualenv
    - # source ~/virtualenv/python3.6.0/bin/activate
    - python --version
    - # python3 --version
    - pip --version
    - ls -R /usr/lib/pyth*
    - # pip3 --version
    - pip install --upgrade flake8
    - flake8 . --count --max-line-length=127 --statistics --exit-zero
    - #  install:
    - ls
before_script:
    flake8 . --count --max-line-length=127 --statistics --exit-zero
script:
    - ls  # a basic noop
notifications:
    on_success: change
    on_failure: always
