sudo: true
language: scala  # NOT a Python repo!
scala:
   - 2.11.2
#language: python
#python:
#    - "2.7.13"
#    - "3.6.0"
#   - "nightly"  # currently points to 3.7-dev
# command to install dependencies
before_install:
    - # source install_python3.sh
    - echo $HOME
    - pwd
    - # cd /
    - # pwd
    - # mkdir Python_3.6.0
    - # cd Python_3.6.0
    - wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.6.0.tar.bz2
    - tar xjf python-3.6.0.tar.bz2 /  # creates ./home and ./opt
    - ls home
    - ls opt
    - # source python-3.6.0/bin/activate
    - # source ~/virtualenv/python3.6.0/bin/activate
    - python -V
    - pip -V
before_script:
    flake8 . --count --max-line-length=127 --statistics --exit-zero
script:
    - true  # a basic noop
notifications:
    on_success: change
    on_failure: always
