sudo: false
language: scala  # NOT a Python repo!
scala:
   - 2.9.3
   - 2.10.4
   - 2.11.2
#language: python
#python:
#    - "2.7.13"
#    - "3.6.0"
#   - "nightly"  # currently points to 3.7-dev
# command to install dependencies
before_install:
    - python -V     # Python 2.7.3 !!!
    - # python3 -V  # Error!
    - pip -V
    - pip3 -V
    - ls
    - tar xjf python-3.6.0.tar.bz2 --directory .
    - ls
    - source ~/virtualenv/python3.6.0/bin/activate
    - python --version
    - pip --version
    - pip install --upgrade flake8
    - flake8 . --count --max-line-length=127 --statistics --exit-zero
install:
    -ls
before_script:
    flake8 . --count --max-line-length=127 --statistics --exit-zero
script:
    - ls  # a basic noop
notifications:
    on_success: change
    on_failure: always
