sudo: false
language: scala  # NOT a Python repo!
scala:
   - 2.11.2
#language: python
#python:
#    - "2.7.13"
#    - "3.6.0"
#   - "nightly"  # currently points to 3.7-dev
# command to install dependencies
before_install:
    - source install_python3.sh
before_script:
    flake8 . --count --max-line-length=127 --statistics --exit-zero
script:
    - ls  # a basic noop
notifications:
    on_success: change
    on_failure: always
